version: "3"

volumes:
  database-data:
  opensearch-data:

services:
  database:
    image: mariadb:10.6
    command: >
      --innodb-buffer-pool-size=1G
      --optimizer-switch='rowid_filter=off'
      --optimizer-use-condition-selectivity=1
      --query-cache-type=ON
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
    volumes:
      - database-data:/var/lib/mysql

  redis:
    image: redis:7.0
    ports:
      - 6379:6379

  opensearch:
#    build: ./.docker/images/opensearch
    image: opensearchproject/opensearch:2.5.0
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1G -Xmx1G"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "discovery.type=single-node"
      - http.max_content_length=100mb
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
